### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by forever33520** [lkeme/bilibili-pcheartbeat#2]
环境：
window10 x64
node版本：v14.6.0
npm版本：6.14.7

node list:
bilibili-pcheartbeat@0.0.1 D:\迅雷下载\bilibili-pcheartbeat-master
+-- body-parser@1.19.0
+-- express@4.17.1
+-- fs@0.0.1-security
+-- jsdom@16.3.0
`-- path@0.12.7

运行后显示：
server now listening at port 3000
{
  t: {
    id: [ 1, 199, 0, 123456 ],
    device: '["device","device"]',
    ets: 'ets',
    benchmark: 'secret_key',
    time: 'heartbeat_interval',
    ts: 'ts',
    ua: 'ua'
  },
  r: [ 2, 5, 1, 4 ]
}
↓---加密前t数据---↓
{"id":"[1,199,0,123456]","device":"[\"device\",\"device\"]","ets":"ets","benchmark":"secret_key","time":"heartbeat_interval","ts":"ts","ua":"ua"}
↓---加密前r数据---↓
[ 2, 5, 1, 4 ]
↓---加密后s数据---↓
RuntimeError: unreachable
    at __rust_start_panic (<anonymous>:wasm-function[248]:0x23d61)
    at rust_panic (<anonymous>:wasm-function[247]:0x23d58)
    at _ZN3std9panicking20rust_panic_with_hook17h6fe9d3817474ba5aE (<anonymous>:wasm-function[244]:0x23b0a)
    at _ZN3std9panicking18continue_panic_fmt17h1b22eea7f33d6c0aE (<anonymous>:wasm-function[243]:0x239d2)
    at rust_begin_unwind (<anonymous>:wasm-function[242]:0x23956)
    at _ZN4core9panicking9panic_fmt17h2daf88b2616ca2b2E (<anonymous>:wasm-function[283]:0x29e49)
    at _ZN4core6result13unwrap_failed17h5745535442976f56E (<anonymous>:wasm-function[54]:0x5d58)
    at spyder (<anonymous>:wasm-function[102]:0xd0e9)
    at Object.Module.exports.spyder (D:\迅雷下载\bilibili-pcheartbeat-master\enc.js:842:101)
    at encrypt_data (D:\迅雷下载\bilibili-pcheartbeat-master\app.js:27:16)

**Comment by lkeme** [comment]
数据只是示例，具体的参数还得你自己套进去，参数可以看[文档](https://mudew.com/20200722/bilibili-webside-live-broadcast-encryption-heartbeat-request-analysis/)抓包或者看`example.py`文件

**Comment by forever33520** [comment]
已经OK了，安装后用postman试的，误以为出了问题(●ˇ∀ˇ●)
