### ISSUE TITLE
有时候会出现 这个报错 是为什么

### ISSUE THREAD

**Issue by lovezm** [lkeme/bilibili-pcheartbeat#3]
SyntaxError: Unexpected token , in JSON at position 124
    at JSON.parse (<anonymous>)
    at parse (C:\Users\Administrator\Desktop\bilibili\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\Administrator\Desktop\bilibili\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\Administrator\Desktop\bilibili\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\Administrator\Desktop\bilibili\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\Administrator\Desktop\bilibili\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by lkeme** [comment]
提交参数有问题
